//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBH
    {
        public string MaBH { get; set; }
        public string MaHD { get; set; }
        public string MaKH { get; set; }
        public string MaSP { get; set; }
        public System.DateTime NgayBH { get; set; }
        public System.DateTime NgayHenTra { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BaoHanh BaoHanh { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
